### ISSUE TITLE
Youtube commands cause issues

### ISSUE THREAD

**Issue by mubeenkh4u** [Kai0071/A17#104]
**Describe the bug**
The youtube download commands do not work on the VPS. I have had similar issues running this on github codespaces.

Installing FFMPEG doesn't help either!

**To Reproduce**
Send .play <url> or .ytmp3 <url> commands to the bot.

**Expected behavior**
It should play or download the link.

**Screenshots**

.play <url>
![image](https://github.com/Kai0071/A17/assets/95019869/f27ce7f9-4a8a-44e5-b365-433c8944d032)

.ytmp3 <url> (getting stuck at 2.33%)
![image](https://github.com/Kai0071/A17/assets/95019869/81d2c30f-706d-45ad-a793-06fae55ab988)

**Desktop (please complete the following information):**
 - OS: Ubuntu 
 - Browser: SSH Terminal
 - Version: 22.04

**Smartphone (please complete the following information):**
NOT APPLICABLE

**Additional context**

**Comment by Guru322** [comment]
Installing FFMPEG Resolves the issue

**Comment by Guru322** [comment]
Maybe you are not installing Ffmpeg Properly

**Comment by Kai0071** [comment]
See the second screenshot clearly mentioned that "𝐜𝐚𝐧𝐧𝐨𝐭 𝐟𝐢𝐧𝐝 𝐟𝐟𝐦𝐩𝐞𝐠" you need to install ffmpeg on your vps.

**Comment by mubeenkh4u** [comment]
Yea, its a VPS issue. They have blocked the installation of FFMPEG.
Sincerely,
Mubeen Ahmed Khan
