### ISSUE TITLE
Qr

### ISSUE THREAD

**Issue by Riders004** [Kai0071/A17#44]
I'm Latest Version Of WhatsApp Qr Scan Doesn't Support Please Update to OTP Based Linked Device Option

**Comment by Tanujairam-TG** [comment]
Doesn't support means? Give proper screenshot to explain

**Comment by Riders004** [comment]
@Tanujairam-TG Bhai to kese closed kar sakta hai mera issue

**Comment by Tanujairam-TG** [comment]
Give

**Comment by Guru322** [comment]
Soon
